name: showsecret

on:
  workflow_dispatch:

jobs:
  get:
    runs-on: ubuntu-latest
    environment: aiai
    steps:
      - name: get
        run: |
          touch local.txt
          echo "${{ secrets.segredo }}" >> local.txt
          echo "${{ vars.primeira }}" >> local.txt
        

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          path: local.txt
      
        
