name: showsecret

on:
  workflow_dispatch:

jobs:
  get:
    runs-on: ubuntu-latest
    environment: teste
    steps:
      - name: get
        run: |
          mkdir local.txt
          echo ${{ secrets.NOVASECRET }} >> local.txt
          echo ${{ secrets.BANCO }} >> local.txt
        

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          path: local.txt
      
        
